[package]
name = "xtask"
version = "0.0.0"
edition = "2024"
rust-version = "1.88"
publish = false

[dependencies]
anyhow = "1.0.104"
clap = { version = "4.6.6", features = ["derive"] }
diffy = "=0.5.1"
hex = "0.4.3"
openapiv3 = "=2.2.0"
percent-encoding = "2.3.2"
progenitor = { version = "=0.14.0", default-features = false }
reqwest = { version = "=0.13.4", default-features = false, features = ["blocking", "rustls"] }
serde_json = { version = "1.0.151", features = ["preserve_order"] }
sha2 = "0.11.0"
syn = { version = "3.0.3", features = ["full"] }
tempfile = "3.27.0"

[dev-dependencies]
rstest = { version = "0.26.1", default-features = false }
