#![warn(clippy::pedantic)]
#![warn(clippy::cargo)]

#[allow(
    clippy::all,
    clippy::pedantic,
    non_camel_case_types,
    reason = "generated by Progenitor"
)]
pub mod api {
    include!(concat!(env!("OUT_DIR"), "/world_anvil.rs"));
}
